// This file is not intended to be modified.
// It is auto-generated by Firebase Studio.
export const firebaseConfig = {
  "projectId": "studio-3648319522-8b6d6",
  "appId": "1:113522247316:web:a962f87b3d2c1a005a9681",
  "apiKey": "AIzaSyDm56wYLNpDFPzBXJ3ITpLdOsJFhPu5gWc",
  "authDomain": "studio-3648319522-8b6d6.firebaseapp.com",
  "storageBucket": "studio-3648319522-8b6d6.appspot.com",
  "messagingSenderId": "113522247316",
};
