// This file is not intended to be modified.
// It is auto-generated by Firebase Studio.
export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-auth-domain",
  "projectId": "mock-project-id",
  "storageBucket": "mock-storage-bucket",
  "messagingSenderId": "mock-messaging-sender-id",
  "appId": "mock-app-id",
};
